export const actionTypes = {
  // for burfer builder
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  SET_INGREDIENTS: 'SET_INGREDIENTS',
  FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
  // for checkout
  PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
  PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
  PURCHASE_BURGER_FAIL: 'PURCHASE_BURGER_FAIL',
  PURCHASE_INIT: 'PURCHASE_INIT',
  // for orders
  FETCH_ORDERS_START: 'FETCH_ORDERS_START',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL',
  // for login page
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_SET_REDIRECT_PATH: 'AUTH_SET_REDIRECT_PATH',
}
